name: Docker Build
on: [push, pull_request]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Build
        id: build
        uses: luludotdev/docker-build@master
        with:
          image-name: yatb-site
          token: ${{ secrets.GITHUB_TOKEN }}